[package]
name = "emicon"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.41"
serde_json = "1.0.142"
slint = "1.12.1"

[build-dependencies]
slint-build = "1.12.1"
