import { VerticalBox, HorizontalBox } from "std-widgets.slint";

export component Overlay inherits Rectangle {
    in property <string> title: "";
    in property <string> message: "";
    in property <length> max-win-width;

    callback close();
    width: 100%;
    height: 100%;

    scope := FocusScope {   
        
        background-layer := Rectangle {
            z: 0;
            width: 100%;
            height: 100%;
            background: transparent;
            drop-shadow-color: #00000050;
            drop-shadow-blur: 20px;
        }
        
        TouchArea {
            z: 0;
            width: 100%;
            height: 100%;
            clicked => {
                root.close();
            }
        }
        
        card := Rectangle {
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
            z: 2;
            width: root.max-win-width;
            height: content.preferred-height;
            background: white;
            border-radius: 16px;
            drop-shadow-blur: 20px;
            drop-shadow-color: #00000040;
            drop-shadow-offset-y: 10px;
            
            TouchArea { }

            content := VerticalBox {
                padding: 6px;
                spacing: 0px;
                HorizontalBox {
                    padding: 0px;
                    spacing: 0px;
                    height: 28px;
                    Rectangle {
                        width: 28px;
                        Image {
                            source: @image-url("icons/arrow-left.svg");
                            width: 20px;
                            height: 20px;
                            colorize: #212529;
                        }

                        TouchArea {
                            width: parent.width;
                            height: parent.height;
                            mouse-cursor: pointer;
                            clicked => {
                                close();
                            }
                        }
                    }
                }

                VerticalBox {
                    padding: 28px;
                    padding-top: 0px;
                    padding-bottom: 20px;
                    spacing: 26px;
                    Text {
                        text: root.title;
                        font-size: 16px;
                        font-weight: 700;
                        color: #333;
                        horizontal-alignment: center;
                    }

                    Text {
                        max-width: 300px;
                        text: root.message;
                        font-size: 10px;
                        color: #666;
                        wrap: word-wrap;
                        vertical-alignment: top;
                        horizontal-alignment: center;
                    }
                }
            }
        }
    }
    
    init => {
        scope.focus();
    }
}
