import { VerticalBox, HorizontalBox } from "std-widgets.slint";

component Tip inherits Rectangle {
    in property <string> text;

    height: 20px;

    cntnt := HorizontalBox {
        padding: 0px;
        VerticalBox {
            padding: 0px;
            alignment: center;
            Rectangle {
                width: 6px;
                height: 6px;
                border-radius: 5px;
                background: #5977ff;
                drop-shadow-color: #244cff;
                drop-shadow-blur: 9px;
            }
        }

        Text {
            vertical-alignment: center;
            text: root.text;
            font-size: 11px;
            font-weight: 400;
            color: #495057;
        }
    }
}

export component PasswordCard inherits Rectangle {
    in property <int> count: 2;

    width: 320px;

    background: white;
    border-radius: 16px;
    drop-shadow-blur: 15px;
    drop-shadow-color: rgba(0, 0, 0, 0.1);

    VerticalBox {
        spacing: 20px;
        padding: 24px;

        HorizontalBox {
            height: 44px;
            padding: 10px;
            spacing: 8px;
            alignment: center;
            Text {
                vertical-alignment: bottom;
                text: count == 0 ? "Password Safe" : "Warning";
                font-size: 20px;
                font-weight: 600;
                color: count == 0 ? #6ec28a : #ff5959;
            }

            VerticalBox {
                height: 24px;
                padding: 0px;
                padding-bottom: 3px;
                spacing: 0px;
                alignment: end;

                Text {
                    vertical-alignment: bottom;
                    text: count == 0 ? "For Now" : "Leakes Were Found";
                    font-size: 10px;
                    font-weight: 500;
                    font-italic: true;
                    color: #495057;
                }
            }
        }

        if count > 1: Text {
            text: "Your password appeared in HIBP breaches and pastes " + count + " times! Take immediate action to protect your accounts and reduce security risks";
            horizontal-alignment: center;
            wrap: word-wrap;
            font-size: 11px;
            font-weight: 400;
            color: #495057;
        }
        if count == 1: Text {
            text: "Your password was found in a single HIBP breach or paste. It may not seem serious, but you should update it regardless in order to stay secure";
            horizontal-alignment: center;
            wrap: word-wrap;
            font-size: 11px;
            font-weight: 400;
            color: #495057;
        }
        if count == 0: Text {
            text: "Good news! Your password was not found in any HIBP breach or paste. Keep following strong password practices to maintain your security";
            horizontal-alignment: center;
            wrap: word-wrap;
            font-size: 11px;
            font-weight: 400;
            color: #495057;
        }

        Rectangle {
            height: 2px;
            background: @linear-gradient(90deg, transparent 0%, #e9ecef 50%, transparent 100%);
        }

        Text {
            text: "What To Do";
            vertical-alignment: center;
            font-size: 14px;
            font-weight: 600;
            color: #212529;
        }

        if count != 0: VerticalBox {
            padding: 0px;
            padding-left: 20px;
            spacing: 8px;

            Tip {
                text: "Change your password immediately";
            }

            Tip {
                text: "Use a unique password per site";
            }

            Tip {
                text: "Don't reuse old compromised passwords";
            }

            Tip {
                text: "Use a trusted password manager";
            }

            Tip {
                text: "Enable two-factor authentication everywhere";
            }

            Tip {
                text: "Update recovery options and contact info";
            }

            Tip {
                text: "Monitor data breach alerts regularly";
            }
        }
        if count == 0: VerticalBox {
            padding: 0px;
            padding-left: 20px;
            spacing: 8px;

            Tip {
                text: "Keep using strong, unique passwords";
            }

            Tip {
                text: "Enable two-factor authentication for safety";
            }

            Tip {
                text: "Regularly update passwords every few months";
            }

            Tip {
                text: "Stay alert for future breach notifications";
            }
        }
    }
}
