export struct ThemePalette {
    background: color,
    pancard_on: color,
    pancard_off: color,
    accent_off: color,
    accent_on: color,
    foreground: color,
    inactive: color,
}

export global Theme {
    in-out property <ThemePalette> current;

    out property <ThemePalette> dark_theme: {
        background: #1a2022,
        pancard_on: #505e54,
        pancard_off: #3c473f,
        accent_off: #3e614d,
        accent_on: #1c914f,
        foreground: #e4ebe6,
        inactive: #9caaa0,
    };
}